feat: PSR template, auto set reviewer, ssh-agent (#14)
* feat: add PSR toml, templates, and action to clear rc tags

* ci: Render themed badges

* fix: perform the git actions inside the ssh-agent

* ci: auto set reviewer if facsimilab-bot performs an action

* fix: split the run into a seperate step

* ci: add conditions to running the workflow

* ci: Render themed badges

* fix: improve permissions and reviewer workflow

* fix: workflow_dispatch

* ci: Render themed badges

* ci: auto review should be in a separate action

* ci: Render themed badges

* cI: action needs to run after render badges has completed

* ci: Render themed badges

---------

Co-authored-by: FacsimiLab [Bot] <195262995+facsimilab-bot@users.noreply.github.com>

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -12,6 +12,44 @@ concurrency:
 
 jobs:
 
+  # Cleanup the tags by deleting the release candidate tags
+  delete-rc-tags:
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout Repository
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0 # Ensure all tags are fetched
+
+      - name: List and Delete Tags Containing 'rc'
+        id: list_tags
+        run: |
+          echo "Searching for tags containing 'rc'..."
+          TAGS=$(git tag --list "*rc*")
+          echo "Found tags:"
+          echo "$TAGS"
+          echo "## Tags \n\n $TAGS" >> $GITHUB_STEP_SUMMARY
+          if [ -z "$TAGS" ]; then
+            echo "No tags containing 'rc' found."
+            echo "tags_to_delete=" > tags.log
+          else
+            echo "tags_to_delete=$TAGS" > tags.log
+
+            echo "Deleting local tags..."
+            echo $TAGS | xargs -n 1 git tag -d
+
+            echo "Deleting remote tags..."
+            for TAG in $TAGS; do
+              git push origin --delete $TAG || echo "Failed to delete $TAG from remote."
+            done
+          fi
+
+      - name: Success Message
+        run: |
+          echo "Completed deleting all tags containing 'rc'." >> $GITHUB_STEP_SUMMARY
+
+  # Python Semantic Release          
   semantic-release:
     runs-on: ubuntu-latest
 
@@ -33,9 +71,9 @@ jobs:
         uses: python-semantic-release/python-semantic-release@v9.15.2
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
-          git_committer_email: "195262995+facsimilab-bot@users.noreply.github.com"
-          ssh_private_signing_key: ${{ secrets.FACSIMILAB_BOT_SSHKEY }}
-          ssh_public_signing_key: ${{ secrets.FACSIMILAB_BOT_SSH_PUBKEY }}
+          git_committer_email: "62562712+pranavmishra90@users.noreply.github.com"
+          ssh_private_signing_key: ${{ secrets.AUTOMATED_SIGNING_KEY }}
+          ssh_public_signing_key: ${{ secrets.AUTOMATED_SIGNING_PUBKEY }}
           vcs_release: "true"
           changelog: "true"
           commit: "true"
